/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import EnumCidade.Cidade;
import javax.swing.JOptionPane;
import projetofinal.Pessoa.Pessoa;
import projetofinal.Pessoa.PessoaDAO;

/**
 *
 * @author Pg
 */
public class telaCadastro extends javax.swing.JFrame {

    PessoaDAO cadastros = new PessoaDAO();
    
   
   
   
    public telaCadastro() {
        initComponents();
    }
    
    public telaCadastro(PessoaDAO cadastradas)
    {
        initComponents();
        this.cadastros = cadastradas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        objCidade = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        objSexo = new javax.swing.JComboBox<>();
        txtTelefone = new javax.swing.JFormattedTextField();
        objEmpregado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jrenda = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jConheceAtingido = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jAtingido = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jIdade = new javax.swing.JTextField();
        jmsgErroIdade = new javax.swing.JLabel();
        jmsgErroRenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton3.setText("CADASTRAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("VOLTAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel3.setText("CPF:");

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Cidade:");

        jLabel6.setText("Celular:");

        jLabel5.setText("Empregado:");

        objCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CANOAS", "PORTO ALEGRE", "VIAMAO", "CAXIAS DO SUL", "PELOTAS" }));
        objCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                objCidadeActionPerformed(evt);
            }
        });

        jLabel1.setText("Sexo:");

        objSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(51)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        objEmpregado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        objEmpregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                objEmpregadoActionPerformed(evt);
            }
        });

        jLabel7.setText("renda mensal:");

        jLabel8.setText("Conhece alguém atingido: ");

        jConheceAtingido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não", " " }));
        jConheceAtingido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConheceAtingidoActionPerformed(evt);
            }
        });

        jLabel9.setText("A pessoa foi atingida: ");

        jAtingido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        jLabel10.setText("Idade:");

        jIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIdadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(objSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(objCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(objEmpregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrenda, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jmsgErroRenda))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jmsgErroIdade))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                .addComponent(txtCPF, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(142, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jConheceAtingido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jAtingido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmsgErroIdade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(objCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(objEmpregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jmsgErroRenda))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jAtingido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jConheceAtingido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(objSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(467, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    //botão de voltar, que faz a criação da telaPrincipal e desativa esta
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        telaPrincipal telap = new telaPrincipal();
        telap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void objCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_objCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_objCidadeActionPerformed

    
    //BOTÃO DE CADASTRO, onde acontece toda parte do cadastro, validações dos campos, para adicionar
    // uma nova pessoa no nosso PessoaDAO
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
 
        //Guarda as informações das caixas de entrada de dados
        boolean validado = true;
        int idade = 0;
        double renda = 0.0;
        String cidadeEscolhida = (String) objCidade.getSelectedItem();  
        String empregadoEscolha = (String) objEmpregado.getSelectedItem();
        String sexoEscolhido = (String) objSexo.getSelectedItem();
        String nomePessoa = (String) txtNome.getText();
        String cpfPessoa = (String) txtCPF.getText();
        String telefone = (String) txtTelefone.getText();
        String conheceEscolha = (String) jConheceAtingido.getSelectedItem();
        String atingidoEscolha = (String) jAtingido.getSelectedItem();
        
        
        Cidade cidade = cidadeEscolhidaNome(cidadeEscolhida);
        boolean empregado = validacaoEmpregado(empregadoEscolha);
        boolean conheceAtingidoEscolha =  validacaoAtingido(conheceEscolha);
        boolean Atingido =  validacaoAtingido(atingidoEscolha);
        
        
        
        //validação do telefone inserido
        if(!validarTelefone(telefone))
        {
            txtNome.requestFocus();
            validado = false;
        }
        
        //validação do nome inserido
         if(!validarNome(nomePessoa))
         {
             txtNome.requestFocus();
             validado = false;
         }
         
         //validação do CPF
         if(!validarCpf(cpfPessoa))
         {
             txtCPF.requestFocus();
             validado = false;
         }
         
        //validação do campo Idade para inserir o dado corretamente na pessoa
        try{
            String idadeString = (String) jIdade.getText();
             idade = Integer.parseInt(idadeString);
             if(idade < 0)
             {
                jmsgErroIdade.setText("Idade em formato ERRADO insira novamente!");
                jIdade.setText("");
                jIdade.requestFocus();
                validado = false;
             }
        }catch(NumberFormatException e)
        {
            jmsgErroIdade.setText("Idade em formato ERRADO insira novamente!");
            jIdade.setText("");
            jIdade.requestFocus();
            validado = false;
        }
        
        //validação do campo Renda para inserir o dado corretamente na pessoa
        try{
            String rendaString =  jrenda.getText().trim();
            System.out.println("Renda obtida: " + rendaString);
            renda = Double.parseDouble(rendaString);
            
            if(renda < 651.00)
            {
                jmsgErroRenda.setText("Renda em formato ERRADO insira novamente!");
                jrenda.setText("");
                jrenda.requestFocus();
                validado = false;
            }
        }catch(NumberFormatException e)
        {
            jmsgErroRenda.setText("Renda em formato ERRADO insira novamente!");
            jrenda.setText("");
            jrenda.requestFocus();
            validado = false;
        }
        
         
         //Cria um novo objeto pessoa com as informações anteriores e salva no arraylist de cadastros
         Pessoa nova = new Pessoa(nomePessoa,cpfPessoa,idade,cidade,telefone,empregado,sexoEscolhido,renda,Atingido,conheceAtingidoEscolha);
         if(validado)
         {
            JOptionPane.showMessageDialog(null, "CADASTRO CONCLUIDO!");
            cadastros.cadastrar(nova);
            telaPrincipal tlPrincipal = new telaPrincipal(cadastros);
            this.setVisible(false);
            tlPrincipal.setVisible(true);
         }       
    }//GEN-LAST:event_jButton3ActionPerformed
    
    
    
    //Aqui faço a verificação se a pessoa colocou sim ou não na opção de trabalho, 
    //para liberar o campo renda, para digitar sua renda, se colocar não, o campo renda fica desativado
    private void objEmpregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_objEmpregadoActionPerformed
        
        String opcaoSelecionada = (String) objEmpregado.getSelectedItem();
        
        if (opcaoSelecionada.equals("Sim")) 
        {
            jrenda.setEnabled(true); 
        } else 
        {
            jrenda.setEnabled(false); 
            jrenda.setText(""); 
        }
    }//GEN-LAST:event_objEmpregadoActionPerformed

    private void jConheceAtingidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConheceAtingidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jConheceAtingidoActionPerformed

    private void jIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIdadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
               

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastro().setVisible(true);
            }
        });
    }
    
    //Metodo de validação do Numero de telefone inserido
    private boolean validarTelefone(String telefone)
    {
        String cleanTelefone = telefone.replace("_", "").replace(".", "").replace("-", "").replace("(","").replace(")","").trim();
        
        if (cleanTelefone.isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "O campo de CPF não pode estar vazio.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (cleanTelefone.length() != 11) 
        {    
            JOptionPane.showMessageDialog(this, "O Telefone deve ter pelo menos 11 caracteres.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    //função que faz a validação do CPF, para impedir que a pessoa deixe vazio,
    //coloque caracteres indesejados ou não coloque o tamanho ideal
    private boolean validarCpf(String cpf)
    {
         String cleanCpf = cpf.replace("_", "").replace(".", "").replace("-", "").trim();
     
               
        if (cleanCpf.isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "O campo de CPF não pode estar vazio.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if (cleanCpf.length() != 11) 
        {    
            JOptionPane.showMessageDialog(this, "O CPF deve ter pelo menos 14 caracteres.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (cleanCpf.matches("\\d+")) {
            return true; // O input é válido (contém apenas números)
        }  
        else 
        {
            JOptionPane.showMessageDialog(this, "Por favor, insira apenas números.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return false; // O input é inválido
        }
    }
    
    //função que faz a validação do nome da Pessoa, verificando primeiro se ela está NULL
    //depois verifica o comprimento minimo do nome,logo em seguida faz a validação se contém caracteres válidos
    private boolean validarNome(String nome) {
    
    if (nome == null || nome.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "O campo de nome não pode estar vazio.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    
    if (nome.trim().length() < 3) {
        JOptionPane.showMessageDialog(this, "O nome deve ter pelo menos 2 caracteres.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        return false;
    }

   
    if (!nome.matches("[a-zA-Z\\s'-]+")) {
        JOptionPane.showMessageDialog(this, "O nome contém caracteres inválidos.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    return true; 
}
    
    
  
    //Faz a transformação do dado de STRING para
    //enum para assim inserir no objeto pessoa 
    public Cidade cidadeEscolhidaNome(String nomeCidade)
    {
        for(Cidade cidade : Cidade.values())
        {
            if(cidade.getNomeDaCidade().equalsIgnoreCase(nomeCidade.trim())) {
                
                return cidade;
            } 
        }
        return null;
    }
    //validação do campo de emprego, transformando o formato String recebido,
    // para booleano, podendo assim inserir no objeto pessoa
    public boolean validacaoEmpregado(String empregado)
    {
         if(empregado.equals("Sim"))
        {
            return true;
        }
        else
        {
            return false;
        }
    }
    //validacao do campo Atingido, transformando da forma STRING
    // para booleano para assim inserir no objeto pessoa 
    public boolean validacaoAtingido(String resposta)
    {
         if(resposta.equals("Sim"))
        {
            return true;
        }
        else
        {
            return false;
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> jAtingido;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jConheceAtingido;
    private javax.swing.JTextField jIdade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jmsgErroIdade;
    private javax.swing.JLabel jmsgErroRenda;
    private javax.swing.JFormattedTextField jrenda;
    private javax.swing.JComboBox<String> objCidade;
    private javax.swing.JComboBox<String> objEmpregado;
    private javax.swing.JComboBox<String> objSexo;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
